name: Generate 3D terrain from GitHub Contribution Grid

on:
  schedule:
    - cron: "5 0 * * *"  # Runs at 12:05 AM UTC every day
  workflow_dispatch:

  push:
    branches:
      - main 

jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN_GITHUB }}
        
      - name: Generate Contribution Terrain
        uses: eshahhh/contribution-terrain@v1.0.0
        with:
          username: ${{ github.repository_owner }}
          style: terrain
          TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
          
      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        run: |
          git config --local user.email "arqam.mzia@gmail.com"
          git config --local user.name "arqamz"
          git add terrain-arqamz.svg
          git commit -m "Update contribution graph" || echo "No changes to commit"
          
          # Use HTTPS with token to push
          git remote set-url origin https://arqamz:${GITHUB_TOKEN}@github.com/${{ github.repository }}
          git push origin HEAD:main
